### ISSUE TITLE
Integrate Tallycoin Connect

### ISSUE THREAD

**Issue by rootzoll** [raspiblitz/raspiblitz#1450]
Connect a https://tallyco.in donation page directly to your RaspiBlitz :D
https://github.com/djbooth007/tallycoin_connect

**Comment by nyxnor** [comment]
Even if running with `sudo python3 setup.py`, it doesn work because need to put sudo inside the variables to cp, enable, start. So I edited the file with sudo on the commands for it to work. I did not manage to get the API key yet, still dont know what Im doing wrong on the last steps.

**Comment by rootzoll** [comment]
tanks for giving this a try - ca you connect with @djbooth007 to see whats still missing?

**Comment by djbooth007** [comment]
> I did not manage to get the API key yet, still dont know what Im doing wrong on the last steps.

The API key can be generated in the admin dashboard after logging in to https://tallyco.in
Go to Node Connect section and copy the API key. Then, paste it in Tallycoin Connect on your Raspiblitz.
You can also check that your node is synced to the Tallycoin server (give it upto a minute).

> need to put sudo inside the variables to cp, enable, start.

Thanks, will update.

**Comment by rootzoll** [comment]
@nyxnor whats the status on your integration test?

**Comment by nyxnor** [comment]
Same as before. Im reporting in this issue here https://github.com/djbooth007/tallycoin_connect/issues/3

**Comment by nyxnor** [comment]
Ok. Im reporting  here now because I passed that problem with some changes he did.
Now I need to allow ufw. Am I doing something wrong?
```
admin@raspberrypi:~/tallycoin_connect $ sudo python3 setup.py
Created symlink /etc/systemd/system/multi-user.target.wants/tallycoin_connect.service → /etc/systemd/system/tallycoin_connect.service.
Enter your API key at http://127.0.1.1:8123/

sudo ufw allow 8123 comment 'tallycoin HTTP'
sudo ufw status

To                     Action      From
--                     ------      ----
8123                   ALLOW       Anywhere                 # tallycoin HTTP
8123 (v6)              ALLOW       Anywhere (v6)            # tallycoin HTTP
```
![temp](https://user-images.githubusercontent.com/69700936/116697213-7066f300-a9b2-11eb-800c-c4b456cda196.png)

**Comment by rootzoll** [comment]
`127.0.1.1` looks a bit strange  - maybe just a typo.

Firewall basically looks good ... are you sure that the service is running and serving on that port locally on the RaspiBlitz? 
What are you getting when you run `wget 127.0.0.1:8123` or `wget 127.0.1.1:8123` on the terminal?

**Comment by nyxnor** [comment]
My router is on 192.168.1.1. The 127.0.1.1 gets always the [localhost](https://github.com/djbooth007/tallycoin_connect/blob/3fd3fbe8d59f0c0cf46a619a5dc2a84b94db5548/setup.py#L51)
Nginx is ok, I tried with other services and it is fine. Also checked ufw again and it is the same for other services as I set for tallycoin.
```
admin@raspberrypi:~ $ sudo systemctl status tallycoin_connect.service 
● tallycoin_connect.service - Tallycoin Connect
   Loaded: loaded (/etc/systemd/system/tallycoin_connect.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-30 15:31:01 BST; 51ms ago
 Main PID: 3576 (node)
    Tasks: 7 (limit: 4533)
   CGroup: /system.slice/tallycoin_connect.service
           └─3576 /usr/bin/node /home/admin/tallycoin_connect/tallycoin_connect.js

Apr 30 15:31:01 raspberrypi systemd[1]: Started Tallycoin Connect.

admin@raspberrypi:~ $ wget 127.0.1.1:8123
--2021-04-30 15:31:06--  http://127.0.1.1:8123/
Connecting to 127.0.1.1:8123... failed: Connection refused.

admin@raspberrypi:~ $ wget 127.0.0.1:8123
--2021-04-30 15:31:10--  http://127.0.0.1:8123/
Connecting to 127.0.0.1:8123... failed: Connection refused.

admin@raspberrypi:~ $ sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
8123                       ALLOW       Anywhere                   # tallycoin HTTP
8123 (v6)                  ALLOW       Anywhere (v6)              # tallycoin HTTP
```

**Comment by nyxnor** [comment]
I couldnt get this to work on my tests, but @pretyflaco did. You said you just followed the instruction on the tallycoin repo, but if you can just make a small install script to get this thing going.

**Comment by rootzoll** [comment]
PR merged for final testing

**Comment by rootzoll** [comment]
@dennisreimann I see the basic website but login is failing. In logs I see:
```
Dec 21 14:48:00 testlnd systemd[1]: Started Tallycoin Connect daemon.
Dec 21 14:54:35 testlnd npm[241392]: Error: Cannot find module '../encodings'
Dec 21 14:54:35 testlnd npm[241392]: Require stack:
```

Further TODOS to add for v1.7.2:
- [x] add as LND Service as one click install

**Comment by dennisreimann** [comment]
Hmm, I just checked, for me it is working with Tallycoin Connect v1.7.0 and v1.7.1 (see #2835).

Tested on my RaspiBlitz v1.7.1 (Runtime = Node 14.17.6, npm 7.24.2)

**Comment by dennisreimann** [comment]
@rootzoll If this still occurs for you, what are the Node and npm versions on RaspiBlitz v1.7.2?

**Comment by rootzoll** [comment]
TODO: Restest with updated NodeJS see #2840

**Comment by rootzoll** [comment]
OK sweet ... its finally running :D Will be part of v1.7.2
@dennisreimann thanks for hanging in there and putting the work on it

**Comment by dennisreimann** [comment]
Nice, we're looking forward to the release and the feedback we get for our early version of the app. 🚀

**Comment by rootzoll** [comment]
Just an observation to check further - on install during provision I got the report:

```
19067-nginx: [emerg] a duplicate listen [::1]:8125 in /etc/nginx/sites-enabled/tallycoin_connect_tor.conf:5
19068:nginx: configuration file /etc/nginx/nginx.conf test failed
19069:Job for nginx.service failed.
```

Also to check with `sudo nginx -t` after install.

**Comment by dennisreimann** [comment]
@rootzoll Took a look and the port 8125 is only used for the Tallycoin Connect Tor service.

The other services configure the IPv6 listen without the `1`, so maybe we should adapt the nginx config for the tor and tor_ssl snippets like this:

```diff
-listen [::1]:8125;
+listen [::]:8125;
```

**Comment by rootzoll** [comment]
OK looking good now :)

**Comment by rootzoll** [comment]
OK install & recovery checked again - working. Closing for v1.7.2 release.
