### ISSUE TITLE
after 1.7 sphinx does not work

### ISSUE THREAD

**Issue by exfrog** [raspiblitz/raspiblitz#2274]
hi. i noticed my ipad and android sphinx apps didnt seem to be updating after i upgraded blitz to 1.7
i went into the menu to sphinx chat, and get the message 'Your SPHINX SERVER may have problems"
I checked debug and got:
'''
May 05 02:40:28 raspberrypi env[18371]:   throw err;
May 05 02:40:28 raspberrypi env[18371]:   ^
May 05 02:40:28 raspberrypi env[18371]: Error: Cannot find module 'express'
May 05 02:40:28 raspberrypi env[18371]: Require stack:
May 05 02:40:28 raspberrypi env[18371]: - /home/sphinxrelay/sphinx-relay/dist/app.js
May 05 02:40:28 raspberrypi env[18371]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
May 05 02:40:28 raspberrypi env[18371]:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
May 05 02:40:28 raspberrypi env[18371]:     at Module.require (internal/modules/cjs/loader.js:952:19)
May 05 02:40:28 raspberrypi env[18371]:     at require (internal/modules/cjs/helpers.js:88:18)
May 05 02:40:28 raspberrypi env[18371]:     at Object.<anonymous> (/home/sphinxrelay/sphinx-relay/dist/app.js:12:17)
May 05 02:40:28 raspberrypi env[18371]:     at Module._compile (internal/modules/cjs/loader.js:1063:30)
May 05 02:40:28 raspberrypi env[18371]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
May 05 02:40:28 raspberrypi env[18371]:     at Module.load (internal/modules/cjs/loader.js:928:32)
May 05 02:40:28 raspberrypi env[18371]:     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
May 05 02:40:28 raspberrypi env[18371]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
May 05 02:40:28 raspberrypi env[18371]:   code: 'MODULE_NOT_FOUND',
May 05 02:40:28 raspberrypi env[18371]:   requireStack: [ '/home/sphinxrelay/sphinx-relay/dist/app.js' ]
May 05 02:40:28 raspberrypi env[18371]: }
May 05 02:40:28 raspberrypi systemd[1]: sphinxrelay.service: Main process exited, code=exited, status=1/FAILURE
May 05 02:40:28 raspberrypi systemd[1]: sphinxrelay.service: Failed with result 'exit-code'.
'''

I tried turning sphinx off and back on in additional apps and services,
i also tried updating the sphinx relay in the update options.
also, fwiw, there was a npm error during sphinx install/update, but the install procedure continued before i could capture it.

any idea what i can do to fix this?  thanks!
